/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RequestStylistRouteImport } from './routes/request-stylist'
import { Route as ForStylistsRouteImport } from './routes/for-stylists'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CityCitySlugRouteImport } from './routes/city.$citySlug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminStylistsRouteImport } from './routes/_authenticated/admin.stylists'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestStylistRoute = RequestStylistRouteImport.update({
  id: '/request-stylist',
  path: '/request-stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStylistsRoute = ForStylistsRouteImport.update({
  id: '/for-stylists',
  path: '/for-stylists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCitySlugRoute = CityCitySlugRouteImport.update({
  id: '/city/$citySlug',
  path: '/city/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminStylistsRoute =
  AuthenticatedAdminStylistsRouteImport.update({
    id: '/admin/stylists',
    path: '/admin/stylists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-stylists': typeof ForStylistsRoute
  '/request-stylist': typeof RequestStylistRoute
  '/saved': typeof SavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$citySlug': typeof CityCitySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/stylists': typeof AuthenticatedAdminStylistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-stylists': typeof ForStylistsRoute
  '/request-stylist': typeof RequestStylistRoute
  '/saved': typeof SavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$citySlug': typeof CityCitySlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/stylists': typeof AuthenticatedAdminStylistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-stylists': typeof ForStylistsRoute
  '/request-stylist': typeof RequestStylistRoute
  '/saved': typeof SavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$citySlug': typeof CityCitySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/stylists': typeof AuthenticatedAdminStylistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/for-stylists'
    | '/request-stylist'
    | '/saved'
    | '/blog/$slug'
    | '/city/$citySlug'
    | '/blog/'
    | '/admin/stylists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-stylists'
    | '/request-stylist'
    | '/saved'
    | '/blog/$slug'
    | '/city/$citySlug'
    | '/blog'
    | '/admin/stylists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/for-stylists'
    | '/request-stylist'
    | '/saved'
    | '/blog/$slug'
    | '/city/$citySlug'
    | '/blog/'
    | '/_authenticated/admin/stylists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForStylistsRoute: typeof ForStylistsRoute
  RequestStylistRoute: typeof RequestStylistRoute
  SavedRoute: typeof SavedRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CityCitySlugRoute: typeof CityCitySlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-stylist': {
      id: '/request-stylist'
      path: '/request-stylist'
      fullPath: '/request-stylist'
      preLoaderRoute: typeof RequestStylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-stylists': {
      id: '/for-stylists'
      path: '/for-stylists'
      fullPath: '/for-stylists'
      preLoaderRoute: typeof ForStylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$citySlug': {
      id: '/city/$citySlug'
      path: '/city/$citySlug'
      fullPath: '/city/$citySlug'
      preLoaderRoute: typeof CityCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/stylists': {
      id: '/_authenticated/admin/stylists'
      path: '/admin/stylists'
      fullPath: '/admin/stylists'
      preLoaderRoute: typeof AuthenticatedAdminStylistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminStylistsRoute: typeof AuthenticatedAdminStylistsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminStylistsRoute: AuthenticatedAdminStylistsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForStylistsRoute: ForStylistsRoute,
  RequestStylistRoute: RequestStylistRoute,
  SavedRoute: SavedRoute,
  BlogSlugRoute: BlogSlugRoute,
  CityCitySlugRoute: CityCitySlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
